# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "qaGitLab" do |app|
    app.vm.box = "webysther/gitlab-ce-ubuntu-x64-14.04"
    app.vm.network "private_network", ip: "192.168.0.111"
    app.vm.hostname = "gitlab"
    app.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
      end
    end
    config.vm.define "qaHostDocker1" do |app|
      app.vm.box = "treehouses/buster64"
      app.vm.network "private_network", ip: "192.168.0.112"
      app.vm.hostname = "hostdocker1"
      app.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
      end
  end